<a href="https://colab.research.google.com/github/AntaraFirozParsa/Data-Wrangling-basic-/blob/main/Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Create the Messy Dataset**

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Order ID':     [101, 102, 103, 104, 105, 103, 106, 107],
    'Customer Name':['Alice', 'bob', 'Charlie', 'DIANA', 'eve', 'Charlie', None, 'Grace'],
    'Product ':     ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Laptop', 'Keyboard', 'Mouse', 'Webcam'],
    ' Price(USD)':  ['$1200.00', '$25.50', '$75.00', '$300', '1100.00', '$75.00', '$25.50', None],
    'Order Date':   ['2024-01-15', '2024/01/18', '2024-02-15', '2024-01-20',
                     '2024-01-22', '2024-02-15', '2024-01-25', '2024-01-28'],
    'Quantity ':    [1, 3, 2, 1, 1, 2, 4, 1],
    'Category':     ['Electronics', 'electronics', 'Electronics', 'ELECTRONICS',
                     'Electronics', 'Electronics', 'electronics', 'Electronics'],
    'Status':       ['Delivered', 'Pending', 'Delivered', 'Shipped',
                     'Delivered', 'Delivered', 'pending', 'Shipped'],
}

df = pd.DataFrame(data)
print(df)
print("\nShape:", df.shape)

   Order ID Customer Name  Product   Price(USD)  Order Date  Quantity   \
0       101         Alice    Laptop    $1200.00  2024-01-15          1
1       102           bob     Mouse      $25.50  2024/01/18          3
2       103       Charlie  Keyboard      $75.00  2024-02-15          2
3       104         DIANA   Monitor        $300  2024-01-20          1
4       105           eve    Laptop     1100.00  2024-01-22          1
5       103       Charlie  Keyboard      $75.00  2024-02-15          2
6       106          None     Mouse      $25.50  2024-01-25          4
7       107         Grace    Webcam        None  2024-01-28          1

      Category     Status
0  Electronics  Delivered
1  electronics    Pending
2  Electronics  Delivered
3  ELECTRONICS    Shipped
4  Electronics  Delivered
5  Electronics  Delivered
6  electronics    pending
7  Electronics    Shipped

Shape: (8, 8)

## **Audit the Mess**

In [ ]:
print("=== Data Types ===")
print(df.dtypes)

print("\n=== Missing Values ===")
print(df.isnull().sum())

print("\n=== Duplicates ===")
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate Order IDs:", df.duplicated(subset=['Order ID']).sum())

print("\n=== Sample ===")
df.head(8)

=== Data Types ===
Order ID          int64
Customer Name    object
Product          object
 Price(USD)      object
Order Date       object
Quantity          int64
Category         object
Status           object
dtype: object

=== Missing Values ===
Order ID         0
Customer Name    1
Product          0
 Price(USD)      1
Order Date       0
Quantity         0
Category         0
Status           0
dtype: int64

=== Duplicates ===
Duplicate rows: 1
Duplicate Order IDs: 1

=== Sample ===

,Order ID,Customer Name,Product,Price(USD),Order Date,Quantity,Category,Status
0,101,Alice,Laptop,$1200.00,2024-01-15,1,Electronics,Delivered
1,102,bob,Mouse,$25.50,2024/01/18,3,electronics,Pending
2,103,Charlie,Keyboard,$75.00,2024-02-15,2,Electronics,Delivered
3,104,DIANA,Monitor,$300,2024-01-20,1,ELECTRONICS,Shipped
4,105,eve,Laptop,1100.00,2024-01-22,1,Electronics,Delivered
5,103,Charlie,Keyboard,$75.00,2024-02-15,2,Electronics,Delivered
6,106,None,Mouse,$25.50,2024-01-25,4,electronics,pending
7,107,Grace,Webcam,None,2024-01-28,1,Electronics,Shipped

## **Fix Column Names**

In [ ]:
# Strip whitespace and standardize all column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace(r'[^a-z0-9_]', '', regex=True)

print(df.columns.tolist())
# Expected: ['order_id', 'customer_name', 'product', 'priceusd', 'order_date', 'quantity', 'category', 'status']

# Rename the price column to something readable
df.rename(columns={'priceusd': 'price_usd'}, inplace=True)
df.head(8)

['order_id', 'customer_name', 'product', 'priceusd', 'order_date', 'quantity', 'category', 'status']

,order_id,customer_name,product,price_usd,order_date,quantity,category,status
0,101,Alice,Laptop,$1200.00,2024-01-15,1,Electronics,Delivered
1,102,bob,Mouse,$25.50,2024/01/18,3,electronics,Pending
2,103,Charlie,Keyboard,$75.00,2024-02-15,2,Electronics,Delivered
3,104,DIANA,Monitor,$300,2024-01-20,1,ELECTRONICS,Shipped
4,105,eve,Laptop,1100.00,2024-01-22,1,Electronics,Delivered
5,103,Charlie,Keyboard,$75.00,2024-02-15,2,Electronics,Delivered
6,106,None,Mouse,$25.50,2024-01-25,4,electronics,pending
7,107,Grace,Webcam,None,2024-01-28,1,Electronics,Shipped

## **Remove Duplicates**

In [ ]:
print("Before:", df.shape)
df.drop_duplicates(subset=['order_id'], keep='first', inplace=True) #Keep the first occurrence of each duplicate
df.reset_index(drop=True, inplace=True)
print("After:", df.shape)
# Should go from 8 rows to 7 rows

Before: (8, 8)
After: (7, 8)

## **Fix Data Types**

In [ ]:
# --- Price ---
df['price_usd'] = df['price_usd'].astype(str)   # make sure it's string
df['price_usd'] = df['price_usd'].str.replace('$', '')
df['price_usd'] = pd.to_numeric(df['price_usd'], errors='coerce') #pd.to_numeric() → converts text to numbers
                                                                  #errors='coerce' → if something cannot be converted, it becomes NaN
# --- Order Date ---
# Step 1: Convert everything to string and standardize separator
df['order_date'] = df['order_date'].astype(str).str.replace('/', '-')

# Step 2: Convert to datetime (handle mixed formats)
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce', dayfirst=True)

 #Converts the column into datetime format --- filter dates, sort by time, extract year/month/day

# --- Quantity ---
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
df['quantity'] = df['quantity'].fillna(0) #Replaces missing values (NaN) with 0
df['quantity'] = df['quantity'].astype(int) #Converts values to integer

print(df.dtypes)
df.head(7)

order_id                  int64
customer_name            object
product                  object
price_usd               float64
order_date       datetime64[ns]
quantity                  int64
category                 object
status                   object
dtype: object

/tmp/ipykernel_3535/3170594691.py:11: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce', dayfirst=True)

,order_id,customer_name,product,price_usd,order_date,quantity,category,status
0,101,Alice,Laptop,1200.0,2024-01-15,1,Electronics,Delivered
1,102,bob,Mouse,25.5,2024-01-18,3,electronics,Pending
2,103,Charlie,Keyboard,75.0,2024-02-15,2,Electronics,Delivered
3,104,DIANA,Monitor,300.0,2024-01-20,1,ELECTRONICS,Shipped
4,105,eve,Laptop,1100.0,2024-01-22,1,Electronics,Delivered
5,106,None,Mouse,25.5,2024-01-25,4,electronics,pending
6,107,Grace,Webcam,NaN,2024-01-28,1,Electronics,Shipped

## **Standardize Text Columns**

In [ ]:
# Title case for names and products
df['customer_name'] = df['customer_name'].str.strip().str.title()  #Converts text to Title Case (first letter capital)
df['product'] = df['product'].str.strip().str.title()

# Consistent casing for category and status
df['category'] = df['category'].str.strip().str.capitalize() #Only first letter uppercase, rest lowercase
df['status'] = df['status'].str.strip().str.capitalize()

print(df[['customer_name', 'product', 'category', 'status']])

  customer_name   product     category     status
0         Alice    Laptop  Electronics  Delivered
1           Bob     Mouse  Electronics    Pending
2       Charlie  Keyboard  Electronics  Delivered
3         Diana   Monitor  Electronics    Shipped
4           Eve    Laptop  Electronics  Delivered
5          None     Mouse  Electronics    Pending
6         Grace    Webcam  Electronics    Shipped

### **Handle Missing Values**

In [ ]:
df.head(7)
# Check what's still missing
print(df.isnull().sum())

# Price: fill with median (robust to outliers)
df['price_usd'].fillna(df['price_usd'].median(), inplace=True)

# Customer name: fill with 'Unknown'
df['customer_name'].fillna('Unknown', inplace=True)

print("\nMissing after fix:", df.isnull().sum().sum()) #.sum().sum() → total missing values in whole dataset

df.head(7)

order_id         0
customer_name    1
product          0
price_usd        1
order_date       0
quantity         0
category         0
status           0
dtype: int64

Missing after fix: 0

/tmp/ipykernel_3535/2763410494.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['price_usd'].fillna(df['price_usd'].median(), inplace=True)
/tmp/ipykernel_3535/2763410494.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['customer_name'].fillna('Unknown', inplace=True)

,order_id,customer_name,product,price_usd,order_date,quantity,category,status
0,101,Alice,Laptop,1200.0,2024-01-15,1,Electronics,Delivered
1,102,Bob,Mouse,25.5,2024-01-18,3,Electronics,Pending
2,103,Charlie,Keyboard,75.0,2024-02-15,2,Electronics,Delivered
3,104,Diana,Monitor,300.0,2024-01-20,1,Electronics,Shipped
4,105,Eve,Laptop,1100.0,2024-01-22,1,Electronics,Delivered
5,106,Unknown,Mouse,25.5,2024-01-25,4,Electronics,Pending
6,107,Grace,Webcam,187.5,2024-01-28,1,Electronics,Shipped

## **Feature Engineering**

In [ ]:
# Revenue column
df['revenue'] = df['price_usd'] * df['quantity']

# Extract date parts
df['order_month'] = df['order_date'].dt.month_name()
df['order_day'] = df['order_date'].dt.day_name()

# Order size category
df['order_size'] = pd.cut(df['quantity'], bins=[0, 1, 3, np.inf],
                           labels=['Small', 'Medium', 'Large'])

print(df[['order_id', 'product', 'revenue', 'order_month', 'order_size']])

   order_id   product  revenue order_month order_size
0       101    Laptop   1200.0     January      Small
1       102     Mouse     76.5     January     Medium
2       103  Keyboard    150.0    February     Medium
3       104   Monitor    300.0     January      Small
4       105    Laptop   1100.0     January      Small
5       106     Mouse    102.0     January      Large
6       107    Webcam    187.5     January      Small

## **Final Validation**

In [ ]:
print("=== Final Shape ===", df.shape)
print("\n=== Data Types ===\n", df.dtypes)
print("\n=== Missing Values ===\n", df.isnull().sum())
print("\n=== Clean Dataset ===")
df.head(10)

=== Final Shape === (7, 12)

=== Data Types ===
 order_id                  int64
customer_name            object
product                  object
price_usd               float64
order_date       datetime64[ns]
quantity                  int64
category                 object
status                   object
revenue                 float64
order_month              object
order_day                object
order_size             category
dtype: object

=== Missing Values ===
 order_id         0
customer_name    0
product          0
price_usd        0
order_date       0
quantity         0
category         0
status           0
revenue          0
order_month      0
order_day        0
order_size       0
dtype: int64

=== Clean Dataset ===

,order_id,customer_name,product,price_usd,order_date,quantity,category,status,revenue,order_month,order_day,order_size
0,101,Alice,Laptop,1200.0,2024-01-15,1,Electronics,Delivered,1200.0,January,Monday,Small
1,102,Bob,Mouse,25.5,2024-01-18,3,Electronics,Pending,76.5,January,Thursday,Medium
2,103,Charlie,Keyboard,75.0,2024-02-15,2,Electronics,Delivered,150.0,February,Thursday,Medium
3,104,Diana,Monitor,300.0,2024-01-20,1,Electronics,Shipped,300.0,January,Saturday,Small
4,105,Eve,Laptop,1100.0,2024-01-22,1,Electronics,Delivered,1100.0,January,Monday,Small
5,106,Unknown,Mouse,25.5,2024-01-25,4,Electronics,Pending,102.0,January,Thursday,Large
6,107,Grace,Webcam,187.5,2024-01-28,1,Electronics,Shipped,187.5,January,Sunday,Small