<a href="https://colab.research.google.com/github/AntaraFirozParsa/Data-Wrangling-basic-/blob/main/Handling_Date_and_Time_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [ ]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [3]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [4]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [5]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

**Working with Dates**

In [6]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

**1. Extract year**

In [7]:
date['date_year'] = date['date'].dt.year


date.sample(5)

          date  product_id  city_id  orders  date_year
178 2019-04-30        4776       16     100       2019
941 2018-11-11        4108       13       3       2018
155 2019-03-04        3888        0       1       2019
469 2019-11-15        5549       28       2       2019
813 2019-06-12          12       25       1       2019

**Extract month**

In [8]:
date['date_month_no'] = date['date'].dt.month
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

**Extract day**

In [11]:
date['date_day'] = date['date'].dt.day

# day of week
date['date_dow'] = date['date'].dt.dayofweek

# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()


#date.head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

**Extract week of the year**

In [15]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

**Extract Quarter**

In [16]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

**Extract Semester**

In [17]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

**Extract Time elapsed between dates**

In [18]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 4, 18, 13, 28, 56, 146379)

In [19]:
today - date['date']

0     2321 days 13:28:56.146379
1     2803 days 13:28:56.146379
2     2734 days 13:28:56.146379
3     2436 days 13:28:56.146379
4     2659 days 13:28:56.146379
                 ...
995   2749 days 13:28:56.146379
996   2690 days 13:28:56.146379
997   2538 days 13:28:56.146379
998   2603 days 13:28:56.146379
999   2377 days 13:28:56.146379
Name: date, Length: 1000, dtype: timedelta64[ns]

In [20]:
(today - date['date']).dt.days

0      2321
1      2803
2      2734
3      2436
4      2659
       ...
995    2749
996    2690
997    2538
998    2603
999    2377
Name: date, Length: 1000, dtype: int64

**TIME Dataset**

In [23]:
# Months passed

date['months_passed'] = (
    (today.year - date['date'].dt.year) * 12 +
    (today.month - date['date'].dt.month)
)

In [24]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [25]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [26]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [27]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

**Extract Time part**

In [28]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

**Time difference**

In [29]:
today - time['date']

0     4507 days 12:38:56.146379
1     4371 days 13:48:56.146379
2     4857 days 13:07:56.146379
3     4159 days 12:57:56.146379
4     4556 days 14:17:56.146379
                 ...
995   5146 days 12:38:56.146379
996   4467 days 14:14:56.146379
997   4932 days 13:51:56.146379
998   5048 days 13:54:56.146379
999   4320 days 14:03:56.146379
Name: date, Length: 1000, dtype: timedelta64[ns]

In [30]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.894503e+08
1      3.777041e+08
2      4.196921e+08
3      3.593843e+08
4      3.936899e+08
           ...
995    4.446599e+08
996    3.860001e+08
997    4.261747e+08
998    4.361973e+08
999    3.732986e+08
Name: date, Length: 1000, dtype: float64

In [31]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.490839e+06
1      6.295069e+06
2      6.994868e+06
3      5.989738e+06
4      6.561498e+06
           ...
995    7.410999e+06
996    6.433335e+06
997    7.102912e+06
998    7.269955e+06
999    6.221644e+06
Name: date, Length: 1000, dtype: float64

In [32]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      108180.648930
1      104917.815596
2      116581.132263
3       99828.965596
4      109358.298930
           ...
995    123516.648930
996    107222.248930
997    118381.865596
998    121165.915596
999    103694.065596
Name: date, Length: 1000, dtype: float64