<a href="https://colab.research.google.com/github/AntaraFirozParsa/Data-Wrangling-basic-/blob/main/Handling_Mixed_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

data = {
    "Cabin": ["A/5 21171", "C85", "STON/O2. 3101282", "C123", None, None, "E46", None, None],
    "Ticket": ["5", "PC 17599", "6", "113803", "373450", "330877", "17463", "349909", "347742"],
    "number": ["5", "3", "6", "3", "A", "2", "2", "5", "1"],
    "Survived": [0, 1, 1, 1, 0, 0, 0, 0, 1]
}

df = pd.DataFrame(data)
print(df)

              Cabin    Ticket number  Survived
0         A/5 21171         5      5         0
1               C85  PC 17599      3         1
2  STON/O2. 3101282         6      6         1
3              C123    113803      3         1
4              None    373450      A         0
5              None    330877      2         0
6               E46     17463      2         0
7              None    349909      5         0
8              None    347742      1         1

In [9]:
# Convert numeric part
df['number_numerical'] = pd.to_numeric(df['number'], errors='coerce')

# Extract categorical part (like 'A')
df['number_categorical'] = df['number'].where(~df['number'].str.isdigit(), np.nan) #Is this value ONLY digits?
df.head(10)

,Cabin,Ticket,number,Survived,number_numerical,number_categorical
0,A/5 21171,5,5,0,5.0,NaN
1,C85,PC 17599,3,1,3.0,NaN
2,STON/O2. 3101282,6,6,1,6.0,NaN
3,C123,113803,3,1,3.0,NaN
4,None,373450,A,0,NaN,A
5,None,330877,2,0,2.0,NaN
6,E46,17463,2,0,2.0,NaN
7,None,349909,5,0,5.0,NaN
8,None,347742,1,1,1.0,NaN

In [11]:
#Extract number (e.g., 85 from C85)
df['cabin_num'] = df['Cabin'].str.extract('(\d+)') #\d → digit (0–9), + → one or more digits
df['cabin_num'] = pd.to_numeric(df['cabin_num'], errors='coerce')
#Extract category (e.g., C from C85)
df['cabin_cat'] = df['Cabin'].str.extract('([A-Za-z]+)') #[A-Za-z] → letters only
df.head(10)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_7662/2328464223.py:2: SyntaxWarning: invalid escape sequence '\d'
  df['cabin_num'] = df['Cabin'].str.extract('(\d+)')

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,cabin_num,cabin_cat
0,A/5 21171,5,5,0,5.0,NaN,5.0,A
1,C85,PC 17599,3,1,3.0,NaN,85.0,C
2,STON/O2. 3101282,6,6,1,6.0,NaN,2.0,STON
3,C123,113803,3,1,3.0,NaN,123.0,C
4,None,373450,A,0,NaN,A,NaN,NaN
5,None,330877,2,0,2.0,NaN,NaN,NaN
6,E46,17463,2,0,2.0,NaN,46.0,E
7,None,349909,5,0,5.0,NaN,NaN,NaN
8,None,347742,1,1,1.0,NaN,NaN,NaN

In [12]:
df['ticket_num'] = df['Ticket'].str.extract('(\d+)')
df['ticket_num'] = pd.to_numeric(df['ticket_num'], errors='coerce')

df['ticket_cat'] = df['Ticket'].str.extract('([A-Za-z/\.]+)')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_7662/1304718998.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['ticket_num'] = df['Ticket'].str.extract('(\d+)')
/tmp/ipykernel_7662/1304718998.py:4: SyntaxWarning: invalid escape sequence '\.'
  df['ticket_cat'] = df['Ticket'].str.extract('([A-Za-z/\.]+)')

In [14]:
df.head(10)

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,cabin_num,cabin_cat,ticket_num,ticket_cat
0,A/5 21171,5,5,0,5.0,NaN,5.0,A,5,NaN
1,C85,PC 17599,3,1,3.0,NaN,85.0,C,17599,PC
2,STON/O2. 3101282,6,6,1,6.0,NaN,2.0,STON,6,NaN
3,C123,113803,3,1,3.0,NaN,123.0,C,113803,NaN
4,None,373450,A,0,NaN,A,NaN,NaN,373450,NaN
5,None,330877,2,0,2.0,NaN,NaN,NaN,330877,NaN
6,E46,17463,2,0,2.0,NaN,46.0,E,17463,NaN
7,None,349909,5,0,5.0,NaN,NaN,NaN,349909,NaN
8,None,347742,1,1,1.0,NaN,NaN,NaN,347742,NaN